config/routes.rb
FriendsOfLocal::Application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  get "users/new"

  root :to => 'static_pages#home'
  match '/signup', to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  
  match '/about', to: 'static_pages#about'
  match '/help', to: 'static_pages#help'
  match '/privacy', to: 'static_pages#privacy'
  match '/contact', to: 'static_pages#contact'
  match '/report', to: 'static_pages#report'

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :name, :sex, :password, :password_confirmation, :contact, :trip_detail, :introduce, :trip_plan, :profile_photo, :country, :city, :language, :area
  has_secure_password
  before_save { |user| user.email = email.downcase }
  before_save :create_remember_token
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }, :if => :should_validate_password?
  validates :password_confirmation, presence: true, :if => :should_validate_password?
  validates :area, presence: true
  attr_accessor :updating_password

  def should_validate_password?
    updating_password
  end

  def self.search(search)
    if search
      find(:all, :conditions => { :city => search }, :order => 'updated_at DESC')
    else
      find(:all, :order => 'updated_at DESC')
    end
  end


  private
  	def create_remember_token
  		self.remember_token = SecureRandom.urlsafe_base64
  	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

app/controllers/sessions_controller.rb
# encoding: utf-8
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by_email(params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_back_or user
    else
      flash.now[:error] = '帳號或密碼錯誤' # Not quite right!
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_path
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def privacy
  end

  def contact
  end

  def report
  end

end

app/controllers/users_controller.rb
# encoding: utf-8
class UsersController < ApplicationController
  before_filter :signed_in_user, only: [:edit, :update]
  before_filter :correct_user,   only: [:edit, :update]
  def new
  	@user = User.new
  end
  def show
  	@user = User.find(params[:id])
    respond_to do |format|
      format.html
      format.js
    end
  end
  def create
    @user = User.new(params[:user])
    @user.updating_password = true
    if @user.save
      sign_in @user
      flash[:success] = "恭喜您註冊成功！試著編輯您的旅行資料吧！或是修改基本資料更改大頭貼唷！"
      redirect_to @user
    else
      render 'new'
    end
  end
  def edit
    @user = User.find(params[:id])
  end
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      flash[:success] = "您的設定已更新"
      sign_in @user
      redirect_to @user
    else
      render 'edit'
    end
  end
  def index
    @users = User.search(params[:search])

  end


  private

    def signed_in_user
      unless signed_in?
        store_location
        redirect_to signin_path, notice: "請登入"
      end
    end
    def correct_user
      @user = User.find(params[:id])
      redirect_to root_path unless current_user?(@user)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def sign_in(user)
		cookies.permanent[:remember_token] = user.remember_token
		self.current_user = user
	end
	def signed_in?
		!current_user.nil?
	end
	def sign_out
		self.current_user = nil
		cookies.delete(:remember_token)
	end
	def current_user=(user)
		@current_user = user		
	end
	def current_user
		@current_user ||=User.find_by_remember_token(cookies[:remember_token])		
	end
	def current_user?(user)
    	user == current_user
  	end
  	def redirect_back_or(default)
    	redirect_to(session[:return_to] || default)
    	session.delete(:return_to)
  	end
  	def store_location
    	session[:return_to] = request.fullpath
  	end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="">Local Friends</a>
    by Wayne Chu & Tiffany Jheng
  </small>
  <nav>
    <ul>
      <li><%= link_to "關於Local Friends",   about_path %></li>
      <li><%= link_to "聯絡我們", contact_path %></li>
      <li><%= link_to "權利宣告", privacy_path %></li>
      <li><a href="">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "Local Friends", root_path, id: "logo" %>
      <h1 class="subtitle">-在台灣找地陪</h1>
      <nav>
        <ul class="nav pull-right ulstyle">          
          <li><%= link_to "Q&A",    help_path %></li>
          <li><%= link_to "問題回報",    "http://goo.gl/OF3Gw", :target => "_blank" %></li>
          <% if signed_in? %>
            
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <%= current_user.name %> <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "個人檔案", current_user %></li>
                <li><%= link_to "帳號設定", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "登出", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "登入", signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<meta charset="utf-8">
<html>
<head>
  <title>Local Friends <%= yield(:title) %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
	<script type="text/javascript">

	  var _gaq = _gaq || [];
	  _gaq.push(['_setAccount', 'UA-33848406-1']);
	  _gaq.push(['_trackPageview']);

	  (function() {
	    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
	    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
	    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
	  })();
	  
	</script>
</head>
<body>
	<div id="fb-root"></div>
	<script>(function(d, s, id) {
	  var js, fjs = d.getElementsByTagName(s)[0];
	  if (d.getElementById(id)) return;
	  js = d.createElement(s); js.id = id;
	  js.src = "//connect.facebook.net/zh_TW/all.js#xfbml=1&appId=135555543221291";
	  fjs.parentNode.insertBefore(js, fjs);
	}(document, 'script', 'facebook-jssdk'));</script>
	<%= render 'layouts/header' %>
	<div class="container">
		<% flash.each do |key, value| %>
        	<div class="alert alert-<%= key %>"><%= value %></div>
     	<% end %>
	    <%= yield %>
	    <%= render 'layouts/footer' %>
	</div>
</body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<h1>關於Local Friends</h1>
<p>對熱愛旅行的您而言，Local Friends致力於提供一個更便利、更有效的管道，幫助您找到最適合您的在地嚮導。</p>
<p>對熱愛分享的您而言，您可以利用本平台找到更多您能夠幫助的旅行者，分享你對在地的知識與經驗，創造雙方共同且美好的回憶。</p>
<p>Local Friends目前不對任何使用者收費，您可以安心地使用Local Friends的各項功能滿足您的需求，若您認同我們的想法，歡迎您分享Local Friends給朋友知道，我們將會非常感謝您:)</p>

app/views/static_pages/contact.html.erb
<h1>聯絡我們</h1>
<p>您可以用以下方式聯絡我們：</p>
<ul>
<li><a href="https://www.facebook.com/LocalFriendsTW">Facebook</a></li>
<li><a href="mailto:wayne.5540@gmail.com">e-mail</a></li>
<li><a href="http://goo.gl/OF3Gw">意見表</a></li>
</ul>

app/views/static_pages/help.html.erb
<h1>Q&A</h1>
<h3>Q1:地陪是什麼意思？與導遊最大的差別是什麼？</h3>
<p><b>Ans1:</b>所謂「地陪」就是「在地的陪伴者」，也就是當地嚮導的意思，通常指對某一地區有較深刻情感或經驗，願意分享給旅者知道的人，相較於導遊可以提供更在地化的行程。</p>
<h3>Q2:在Local Friends找地陪需要費用嗎？</h3>
<p><b>Ans1:</b>Local Friends提供您找地陪的廣告，我們不會對您或地陪收取費用，但每位地陪都可自行為其提供的旅程訂價，建議您對行程的價位有不清楚的地方可以直接連絡該地陪討論。</p>
<h3>Q3:我想當地陪，有甚麼條件嗎？</h3>
<p><b>Ans1:</b>在Local Friends申請當地陪並不需要任何條件，但為了創造地陪與旅行者雙方共同的美好經驗，您必須是能夠信賴的人、並為您所提供的行程負責，以同理心將最好的一面呈現給旅行者。</p>
</br>
<h3>若以上問題無法解答您的疑惑，可以到<a href="http://goo.gl/OF3Gw" target="_blank">這裡</a>填寫您的疑問，我們會盡快回覆您，謝謝:)
</h3>

app/views/static_pages/home.html.erb
<% provide(:title, 'Home') %>
<div class="center hero-unit">
  <h1>Welcome to Local Friends</h1>
</br>
  <p><b>如果您是熱愛旅行的朋友</b>，您可以在Local Friends找到世界各地的同好，帶您走訪他們最熟悉的故鄉、提供您最在地最特別的體驗，Local Friends現在提供<b>台灣地區的中文地陪</b>，現在就搜尋他們吧。</p>
	<%= form_tag users_path, :method => 'get', :id => "users_search" do %>
		<p>
      <%= select_tag "country" ,options_for_select([['台灣','台灣']]) ,class: "span2 controls controls-row" %>
      <%= select_tag "area" ,options_for_select([['北部','北部'],['中部','中部'],['南部','南部'],['東部','東部'],['離島','離島']]) ,class: "span2 controls controls-row" %>
      <%= select_tag "search" ,options_for_select([['台北','台北',{ :class => '北部' }],['台中','台中',{ :class => '中部' }],['台南','台南',{ :class => '南部' }],['高雄','高雄',{ :class => '南部' }],['基隆','基隆',{ :class => '北部' }],['新竹','新竹',{ :class => '北部' }],['嘉義','嘉義',{ :class => '南部' }],['桃園','桃園',{ :class => '北部' }],['苗栗','苗栗',{ :class => '北部' }],['彰化','彰化',{ :class => '中部' }],['南投','南投',{ :class => '中部' }],['雲林','雲林',{ :class => '中部' }],['屏東','屏東',{ :class => '南部' }],['宜蘭','宜蘭',{ :class => '北部' }],['花蓮','花蓮',{ :class => '東部' }],['台東','台東',{ :class => '東部' }],['澎湖','澎湖',{ :class => '離島' }],['金門','金門',{ :class => '離島' }],['連江','連江',{ :class => '離島' }]],params[:search]),class: "span3 controls controls-row"
      %>
		    <%= submit_tag "找地陪", :name => nil, class: "btn btn-large btn-primary" %>
		</p>
    <% end %>


  <% if !signed_in? %>

    </br>
    <h2>---OR---</h2>

    <p><b>如果您是熱愛分享的朋友</b>，您可以利用本平台找到更多您能夠幫助的旅行者，分享你對在地的知識與經驗，行程規劃和收費與否取決於您的選擇，歡迎加入Local Friends成為地陪，一起創造旅行的美好回憶。</p>
  	<%= link_to "註冊成為地陪", signup_path, class: "btn btn-large btn-info" %>
  <% end %>

  <div id="fb-root"><p></p></div>
  <hr>
  <h2>---AND---</h2>

  <p>加入粉絲團，讓大家幫你一起找地陪&旅行家</p>
  <div class="fb-like-box" data-href="https://www.facebook.com/LocalFriendsTW" data-width="570" data-height="190" data-show-faces="true" data-stream="false" data-header="false"></div>
  <hr>

  <span style="color:gray;"><i>------不建議使用IE系列瀏覽器------</i></span>
<script type="text/javascript">
  $("#search").chained("#area");
</script>
</div>

app/views/static_pages/privacy.html.erb
<h1>Local Friends 權利宣告</h1>
<p>Local Friends致力於提供您更好的使用經驗，我們不會將您的資料轉作第三方用途，也會盡力保障您個人資料的安全性，但網路安全無法保證，因此我們並不承擔任何資料安全性的責任。此外，您也應注意您在本平台上或是以本平台為媒介的任何活動都屬於您的私人活動，本平台不對您的行為負任何責任，因此請您在使用時仍要注意自身安全以及誠信原則，以保障您的權利，謝謝。</p>

app/views/static_pages/report.html.erb
<h1>StaticPages#report</h1>
<p>Find me in app/views/static_pages/report.html.erb</p>

app/views/users/_contact.html.erb
      <div id="contact">
        <h2>
          聯絡方式：
        </h2>
        <%= raw @user.contact %>
      </div>
  

app/views/users/_edit_profile.html.erb
    <div class="information">
      <div id="introduce">
        <h2>
          地陪簡介：(*旅行者搜尋您時會立即看到您的簡介)
        </h2>
        <%= form_for(@user) do |f| %>
          <%= f.text_field :introduce, class: "form_text" %>
          <%= f.submit "確定更改", class: "btn" %>
        
      </div>
      <div id="trip_plan">
        <h2>
          旅行安排與建議：(*輸入您的行程安排，或是對旅行者的建議，此外若地陪服務需要收費記得在此填寫)
        </h2>
        <%= f.text_field :trip_plan, class: "form_text" %>
        <%= f.submit "確定更改", class: "btn" %>
        
      </div>
      
        <% end %>
        <script type="text/javascript">
          $('#user_introduce').wysihtml5({"font-styles": false});
          $('#user_trip_plan').wysihtml5();

        </script>
      </div>
      
    </div>

app/views/users/_introduce.html.erb
<div id="introduce">
        <h2>
          地陪簡介：
        </h2>
        <p><%= raw @user.introduce %></p>
</div>

app/views/users/_trip_detail.html.erb
      <div id="guide">
        <h2>
          收費方式：
        </h2>
        <p><%= raw @user.trip_detail %></p>
      </div>

app/views/users/_trip_plan.html.erb
      <div id="trip_plan">
        <h2>
          旅行安排與建議：
        </h2>
        <p><%= raw @user.trip_plan %></p>
      </div>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %> 
<h1>設定您的帳號</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      
      <%= f.label :name, "姓名" %>
      <%= f.text_field :name %>

      <%= f.label :email, "電子信箱(帳號名稱)" %>
      <%= f.text_field :email %>

      <%= f.label :area, "所在區域(台灣)" %>
      <%= f.select :area ,options_for_select([['北部','北部'],['中部','中部'],['南部','南部'],['東部','東部'],['離島','離島']]), {}, { :class => 'span3 controls controls-row' } %> 
      <%= f.select :city ,options_for_select([['台北','台北',{ :class => '北部' }],['台中','台中',{ :class => '中部' }],['台南','台南',{ :class => '南部' }],['高雄','高雄',{ :class => '南部' }],['基隆','基隆',{ :class => '北部' }],['新竹','新竹',{ :class => '北部' }],['嘉義','嘉義',{ :class => '南部' }],['桃園','桃園',{ :class => '北部' }],['苗栗','苗栗',{ :class => '北部' }],['彰化','彰化',{ :class => '中部' }],['南投','南投',{ :class => '中部' }],['雲林','雲林',{ :class => '中部' }],['屏東','屏東',{ :class => '南部' }],['宜蘭','宜蘭',{ :class => '北部' }],['花蓮','花蓮',{ :class => '東部' }],['台東','台東',{ :class => '東部' }],['澎湖','澎湖',{ :class => '離島' }],['金門','金門',{ :class => '離島' }],['連江','連江',{ :class => '離島' }]]), {}, { :class => 'span3 controls controls-row' }
      %>

      
      <%= f.label :password, "變更密碼(留空白表示不變更)" %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "確認密碼" %>
      <%= f.password_field :password_confirmation %>

      <img src=<%if @user.profile_photo==""%><%= "http://goo.gl/gdibQ" %><%else %> <%= @user.profile_photo || "http://goo.gl/gdibQ" %><%end%> alt=<%= @user.name %> class="change_photo">
      <%= f.label :profile_photo, "更換大頭貼(網路圖片連結)" %>
      <h5>取得連結教學：1.找到想要的圖片→2.圖片上點選右鍵→3.「複製圖片連結」→4.貼在下方空格→5.完成！</h5>
      <%= f.text_field :profile_photo %>

      <%= f.submit "確定更改", class: "btn btn-large btn-primary" %>
    <% end %>
    <script type="text/javascript">

  $("#user_city").chained("#user_area");
</script>
  </div>
</div>

app/views/users/index.html.erb
<h1>地陪</h1>

<div class = "users">
  
  <% @users.each do |user| %>
	  <div id="<%= user.sex %>" class="grapper">
	  	<a class="div_button" href="users/<%= user.id %>">
	    <div class="users_photo">
	      <img src=<%if user.profile_photo==""%><%= "http://goo.gl/gdibQ" %><%else %> <%= user.profile_photo || "http://goo.gl/gdibQ" %><%end%> alt=<%= user.name %>>
	    </div>
	    <div class="basic_info" >
	      <h1>
	        <%= user.name %>
	      </h1>
	      <span id="<%= user.sex %>">
	        <%= user.sex %>
	      <span>
	      
	      <p id="<%= user.area %>, <%= user.city %>">
	        <b>我在台灣的</b> <%= user.area %> <b>→</b> <%= user.city %></p>

	      <p>
	        <b>地陪簡介:</b>
	        <%= raw user.introduce %>
	      </p>
	    </div>
	    
	    <div class="clear"></div>
	  </div>
	  </a>
  <% end %>

</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>註冊</h1>
<div id="fb-root"></div>
<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name, "姓名" %>
      <%= f.text_field :name %>

      <%= f.label :email, "電子信箱(帳號名稱)" %>
      <%= f.text_field :email %>

      <%= f.label :sex, "性別" %>
      <%= f.select :sex ,options_for_select([['先生','male'],['女士','female']]) %>

      <%= f.label :area, "所在區域(台灣)" %>
      <%= f.select :area ,options_for_select([['北部','北部'],['中部','中部'],['南部','南部'],['東部','東部'],['離島','離島']]), {}, { :class => 'span3 controls controls-row' } %>
      <%= f.select :city ,options_for_select([['台北','台北',{ :class => '北部' }],['台中','台中',{ :class => '中部' }],['台南','台南',{ :class => '南部' }],['高雄','高雄',{ :class => '南部' }],['基隆','基隆',{ :class => '北部' }],['新竹','新竹',{ :class => '北部' }],['嘉義','嘉義',{ :class => '南部' }],['桃園','桃園',{ :class => '北部' }],['苗栗','苗栗',{ :class => '北部' }],['彰化','彰化',{ :class => '中部' }],['南投','南投',{ :class => '中部' }],['雲林','雲林',{ :class => '中部' }],['屏東','屏東',{ :class => '南部' }],['宜蘭','宜蘭',{ :class => '北部' }],['花蓮','花蓮',{ :class => '東部' }],['台東','台東',{ :class => '東部' }],['澎湖','澎湖',{ :class => '離島' }],['金門','金門',{ :class => '離島' }],['連江','連江',{ :class => '離島' }]]), {}, { :class => 'span3 controls controls-row' }
      %>

      <%= f.label :password, "密碼" %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "確認密碼" %>
      <%= f.password_field :password_confirmation %>
      <%= f.label :join_fb, "加入Local Friends粉絲團，讓大家幫你一起找地陪&旅行家" %>
      <div class="fb-like" data-href="https://www.facebook.com/LocalFriendsTW" data-send="false" data-width="450" data-show-faces="true"></div>
      <hr>
      
      <%= f.submit "建立帳號", class: "btn btn-large btn-primary" %>
    <% end %>
    <script type="text/javascript">

  $("#user_city").chained("#user_area");
</script>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>

<div class="row">
  <div class="">
    <div class="profile_photo">
      <img src=<%if @user.profile_photo==""%><%= "http://goo.gl/gdibQ" %><%else %> <%= @user.profile_photo || "http://goo.gl/gdibQ" %><%end%> alt=<%= @user.name %>>
    </div>
    <% if current_user?(@user) %>
    <div id="edit_profile">
        <%= link_to "修改個人資料", edit_user_path(current_user) %>
    </div>
    <% end %>
    <div class="basic_info">
      <h1>
        <%= @user.name %>
      </h1>
      <span>
        <%= @user.sex %>
      <span>
      
      <p>
        <b>所在國家(區域):</b> <%= @user.area %>
      </p>
      <p><b>所在城市:</b> <%= @user.city %></p>
      <p><b>E-mail:</b> <%= @user.email %></p>

    </div>
    <div class="clear"></div>
    <% if current_user?(@user) %>
      <%= link_to "修改旅行資料", user_path(current_user), :remote => true,  :style => 'float: right;',  "data-type" => "script" %>
    <% end %>
    <div id="information" class="information">
      <%= render 'users/introduce' %>
      <%= render 'users/trip_plan' %>
      <hr>
      <div id="fb_share">
        <h4>你的朋友或許會喜歡這趟旅程？</h4>
      </br>
        <h3>按個<div class="fb-like" data-send="false" data-layout="button_count" data-width="100" data-show-faces="true"></div></h3>
      </br>
        <h4>與他們一起分享這位在地好地陪吧！</h4>
        
      </div>
    </div>
  </div>
</div>

app/views/users/show.js.erb
$('#information').html("<%= escape_javascript(render :partial => 'edit_profile') %>");